language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

services:
  - memcached
  
before_script:
  - composer install
  - php bootstrap.php

notifications:
  email: false
script: phpunit --configuration phpunit.xml --coverage-text